### ISSUE TITLE
mido-play/mido-ports failing on OSX

### ISSUE THREAD

**Issue by pierz** [olemb/mido#152]
I installed mido and python-rtmidi as explained on installation but when I run `mido-play` or `mido-ports` it generates errors:

> Traceback (most recent call last):
>   File "/usr/local/bin/mido-ports", line 18, in <module>
>     print_ports('Available input Ports:', mido.get_input_names())
>   File "/usr/local/lib/python2.7/site-packages/mido/backends/backend.py", line 168, in get_input_names
>     devices = self._get_devices(**self._add_api(kwargs))
>   File "/usr/local/lib/python2.7/site-packages/mido/backends/backend.py", line 162, in _get_devices
>     return self.module.get_devices(**self._add_api(kwargs))
>   File "/usr/local/lib/python2.7/site-packages/mido/backends/rtmidi.py", line 49, in get_devices
>     rtapi = _get_api_id(api)
>   File "/usr/local/lib/python2.7/site-packages/mido/backends/rtmidi.py", line 33, in _get_api_id
>     return rtmidi.API_UNSPECIFIED
> AttributeError: 'module' object has no attribute 'API_UNSPECIFIED'

**Comment by belm0** [comment]
Not specific to OS X.   As I discovered today it's due to installation of the wrong rtmidi package.

Incredibly, there are 3 rtmidi Python bindings in pypi, with confusingly similar names.  Of the three, none acknowledge existence of the other projects.   And two of them use the same module name :(

https://pypi.python.org/pypi/python-rtmidi   **<-- you want this**
https://pypi.python.org/pypi/rtmidi
https://pypi.python.org/pypi/rtmidi-python
