### ISSUE TITLE
Load midi file and Save file occurs AttributeError while "UnknownMetaMessage" in file

### ISSUE THREAD

**Issue by exeex** [olemb/mido#159]
this is my code
```
from mido import MidiFile
mid = MidiFile("test_file/imagine_dragons-believer.mid")
mid.save("gg.mid")
```

And the test file is here: [imagine_dragons-believer.zip](https://github.com/olemb/mido/files/1890344/imagine_dragons-believer.zip)

This is a complex karaoke midi file which include lyrics and a lot "UnknownMetaMessage"
Mido can load it correctly.
However cannot save it correctly.

The error massages are
```
Traceback (most recent call last):
  File "C:/Users/xray0/Desktop/mimi/mimi/gg.py", line 18, in <module>
    mid.save("gg.mid")
  File "C:\Users\xray0\PycharmProjects\untitled\venv\lib\site-packages\mido-1.2.8-py3.6.egg\mido\midifiles\midifiles.py", line 416, in save
    self._save(file)
  File "C:\Users\xray0\PycharmProjects\untitled\venv\lib\site-packages\mido-1.2.8-py3.6.egg\mido\midifiles\midifiles.py", line 429, in _save
    write_track(outfile, track)
  File "C:\Users\xray0\PycharmProjects\untitled\venv\lib\site-packages\mido-1.2.8-py3.6.egg\mido\midifiles\midifiles.py", line 257, in write_track
    raw = msg.bytes()
  File "C:\Users\xray0\PycharmProjects\untitled\venv\lib\site-packages\mido-1.2.8-py3.6.egg\mido\midifiles\meta.py", line 560, in bytes
    + self.data)
AttributeError: 'UnknownMetaMessage' object has no attribute 'data'
```

This would be easily fixed by add try-except to handle the AttributeError

**Comment by olemb** [comment]
I've committed a fix to the master branch. It now loads and saves your file successfully.
 
Thanks for reporting this!
