### ISSUE TITLE
OSError: dlopen(libportmidi.dylib, 6): image not found

### ISSUE THREAD

**Issue by aesthese** [olemb/mido#44]
After upgrading from Yosemite to OS X El Capitan 10.11.4 I get the following error. My code worked perfectly just before the upgrade.

`Traceback (most recent call last):
  File "[REDACTED].py", line 6, in <module>
    inport = mido.open_input('[REDACTED]')
  File "/Library/Python/2.7/site-packages/mido/backends/backend.py", line 112, in open_input
    return self.module.Input(name, **self._add_api(kwargs))
  File "/Library/Python/2.7/site-packages/mido/backends/backend.py", line 63, in module
    self.load()
  File "/Library/Python/2.7/site-packages/mido/backends/backend.py", line 79, in load
    self._module = _import_module(self.name)
  File "/Library/Python/2.7/site-packages/mido/backends/backend.py", line 25, in _import_module
    return importlib.import_module(module, package)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/mido/backends/portmidi.py", line 15, in <module>
    from . import portmidi_init as pm
  File "/Library/Python/2.7/site-packages/mido/backends/portmidi_init.py", line 20, in <module>
    lib = CDLL(dll_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libportmidi.dylib, 6): image not found`

Easier to read screenshot:
https://imgur.com/bf3rbOd

**Comment by olemb** [comment]
It looks like PortMidi has gotten lost in the upgrade. Can you remember how you installed it?

**Comment by adarob** [comment]
I just installed with HomeBrew for the first time and got this same error.

**Comment by olemb** [comment]
It should work if you install this:

http://brewformulas.org/Portmidi

**Comment by adarob** [comment]
I have installed PortMidi with HomeBrew. Any other ideas?

**Comment by olemb** [comment]
Are you still getting the same error?

An alternative is to switch to RtMidi (the python-rtmidi package). I'm not
sure how easy this is to install on OSX though.

**Comment by adarob** [comment]
Yes, same error. RtMidi does indeed work.

**Comment by olemb** [comment]
Ah, good.

I'm not sure why Mido can't find the PortMidi library. Perhaps the library
path has not been updated?

Anyway, RtMidi is better in every way so I'd recommend sticking with it.

**Comment by olemb** [comment]
OK, I just installed homebrew here and got the same error you did. Then I did "brew install portmidi" and now it works. I wonder why it didn't work for you.

**Comment by adarob** [comment]
The issue was that I hadn't set up my homebrew symlinks correctly.

**Comment by olemb** [comment]
Ah, that makes sense.

I should add something about Homebrew to the docs. It seems to be the best
way to install PortMidi.

**Comment by lambdamusic** [comment]
I'm on OSX 10.11.5, reinstalled PortMidi using brew but keep getting this error:

```OSError: dlopen(libportmidi.dylib, 6): image not found```

**Comment by lambdamusic** [comment]
FYI I managed to get it running using python rtmidi: `pip install python-rtmidi`
..and then `mido.set_backend('mido.backends.rtmidi')` as per the official docs.

**Comment by olemb** [comment]
Glad to hear you got it working!

RtMidi is what I would recommend this days. It has all the features of PortMidi and more (such as virtual ports). I would like to make it the default but I need to make sure I don't break people's installations, so it will have to wait until at least 1.2.

**Comment by H4CKL0RD** [comment]
I undestand this issue is closed but I am also getting the same issue! I tried both methods listed before and none worked. Just to clarify I am using pycharm.Error here:   
`  import vlc
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/vlc.py", line 210, in <module>
    dll, plugin_path  = find_lib()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/vlc.py", line 191, in find_lib
    ctypes.CDLL('libvlccore.dylib')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libvlccore.dylib, 6): image not found

Process finished with exit code 1
`
