### ISSUE TITLE
OSError: libportmidi.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by prashant2018** [olemb/mido#45]
Hi,
I am trying to run the example but getting OSError after the following statement. 

> output = mido.open_output()

gives this error.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mido/backends/backend.py", line 133, in open_output
    return self.module.Output(name, **self._add_api(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/mido/backends/backend.py", line 63, in module
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/mido/backends/backend.py", line 79, in load
    self._module = _import_module(self.name)
  File "/usr/local/lib/python2.7/dist-packages/mido/backends/backend.py", line 25, in _import_module
    return importlib.import_module(module, package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/mido/backends/portmidi.py", line 15, in <module>
    from . import portmidi_init as pm
  File "/usr/local/lib/python2.7/dist-packages/mido/backends/portmidi_init.py", line 20, in <module>
    lib = CDLL(dll_name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libportmidi.so: cannot open shared object file: No such file or directory`

**Comment by olemb** [comment]
To use ports you need to install either PortMidi or RtMidi:

    https://mido.readthedocs.io/en/latest/installing.html

**Comment by dirkk0** [comment]
Essentially I needed this on a RaspberryPi:
```
sudo apt-get install libasound2-dev
sudo apt-get install libjack-dev
sudo pip install --pre python-rtmidi
sudo ln -s /usr/lib/libportmidi.so.0 /usr/lib/libportmidi.so
```
(via [this post]( http://raspberrypi.stackexchange.com/questions/30153/oserror-libportmidi-so-cannot-open-shared-object-file-no-such-file-or-directo) )

**Comment by cjappl** [comment]
@prashant2018 has this issue been resolved? There has been no action on this for a long time

**Comment by cjappl** [comment]
Moving to close
