### ISSUE TITLE
"IOError: no default port found" when running bin/mido-play

### ISSUE THREAD

**Issue by MikeBosw** [olemb/mido#69]
Hi! Apologies for such a n00b question, but I'm having trouble getting past this obstacle.

I've brew installed portmidi. I've also confirmed that pygame **_is able_** to play a midi file using its mixer module.

However, running the given mido-play example produces the error message in the subject of this issue. Do you know what step I'm missing? The stack trace is reproduced below:

`Traceback (most recent call last):
  File "./bin/mido-play", line 92, in <module>
    main()
  File "./bin/mido-play", line 74, in main
    with mido.open_output(args.output_port) as output:
  File "/usr/local/lib/python2.7/site-packages/mido/backends/backend.py", line 111, in open_output
    return self.module.Output(name, **self._add_api(kwargs))
  File "/usr/local/lib/python2.7/site-packages/mido/ports.py", line 263, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mido/ports.py", line 53, in __init__
    self._open(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/mido/backends/portmidi.py", line 116, in _open
    device = _get_default_device(opening_input)
  File "/usr/local/lib/python2.7/site-packages/mido/backends/portmidi.py", line 67, in _get_default_device
    raise IOError('no default port found')
IOError: no default port found`

**Comment by olemb** [comment]
Hi,

I tried here and I get the same error. Fortunately you can use `-o` flag to select a port:

    mido-play -o 'Some Port' somefile.mid

I've looked into this and I don't understand why it happens. The Pygame and PortMidi backends both end up calling the same function, pm_GetDefaultOutputDeviceID(), but with different results:

```python
>>> import mido.backends.portmidi
>>> mido.backends.portmidi.pm.lib.Pm_GetDefaultOutputDeviceID()
0
```

```python
>>> import pygame.midi
>>> pygame.midi.init()
>>> pygame.midi._pypm.GetDefaultOutputDeviceID()
-1
```

(`-1` means no port found.)

**Comment by olemb** [comment]
It's worse than I thought. On my system Pygame doesn't find any ports at all. (I haven't tried with physical MIDI devices, but I'll do later today.)

I've looked into this a bit more and found that Pygame bundles its own version of the PortMidi library. This may be a different version or compiled with different options, which would explain why the PortMidi backend works.

May I ask which version of Pygame you're using? I have 1.9.2b8. (You can find this in `pygame.__version__`.)

**Comment by rdoursenaud** [comment]
I don't have this behavior with v1.3.0 so I guess it's been fixed.

Feel free to reopen if it's not for you.
